### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by threehappypenguins** [cylab-tw/raccoon#17]
When I do `npm install`, I get:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'commander@10.0.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/user/raccoon/node_modules/dicom-to-json
npm ERR! command failed
npm ERR! command sh -c run-script-os
npm ERR! > dicom-to-json@1.2.1 install:linux
npm ERR! > npx prebuild-install -r napi || npx cmake-js compile --CDWITH_LIBICONVINC:PATH="/usr/local/apps" --CDDCMTK_ENABLE_CHARSET_CONVERSION:STRING="libiconv" --CDDCMTK_WITH_ICONV:BOOL=1 --CDnapi_build_version=4
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=arm64 libc= platform=linux)
npm ERR! internal/modules/cjs/loader.js:818
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'bluebird'
npm ERR! Require stack:
npm ERR! - /home/user/raccoon/node_modules/cmake-js/lib/downloader.js
npm ERR! - /home/user/raccoon/node_modules/cmake-js/lib/dist.js
npm ERR! - /home/user/raccoon/node_modules/cmake-js/lib/cMake.js
npm ERR! - /home/user/raccoon/node_modules/cmake-js/lib/buildSystem.js
npm ERR! - /home/user/raccoon/node_modules/cmake-js/lib/index.js
npm ERR! - /home/user/raccoon/node_modules/cmake-js/bin/cmake-js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/home/user/raccoon/node_modules/cmake-js/lib/downloader.js:2:15)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/user/raccoon/node_modules/cmake-js/lib/downloader.js',
npm ERR!     '/home/user/raccoon/node_modules/cmake-js/lib/dist.js',
npm ERR!     '/home/user/raccoon/node_modules/cmake-js/lib/cMake.js',
npm ERR!     '/home/user/raccoon/node_modules/cmake-js/lib/buildSystem.js',
npm ERR!     '/home/user/raccoon/node_modules/cmake-js/lib/index.js',
npm ERR!     '/home/user/raccoon/node_modules/cmake-js/bin/cmake-js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2024-03-04T22_33_19_361Z-debug-0.log
```

**Comment by Chinlinlee** [comment]
Thanks for reporting this issue! I think the problem is caused by the lack of prebuilt binaries for your OS in the `dicom-to-json` module, so it runs the rebuild command.
Could you try to install `bluebird` (npm install bluebird) before running `npm install`?

Additionally, this repository is unmaintained. I recommend that you use the updated version [raccoon-dicom](https://github.com/Chinlinlee/raccoon-dicom.git).
